server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: userLogin
  redis: 
    database: 0
    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 6
      max-idle: 6
      max-wait: -1
      min-idle: 0
    timeout: 3000
  datasource:
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: "wsy"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
